# Generated by Django 3.2.7 on 2021-09-13 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210908_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 13, 4, 51, 6, 276797, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
